from utilities.vision import Vision

# TODO:

# Load all images
again = Vision("again.png")
lock = Vision("lock.png")
resume = Vision("resume.png")
ok_button = Vision("ok_button.jpg")
restore_stamina = Vision("stamuse.png")
startbutton = Vision("start.png")
skip = Vision("skip.png")
dmg = Vision("dmg.png")
duplicate = Vision("duplicate.jpg")
reconnect = Vision("reconnect.png")
result = Vision("result.png")
mission = Vision("mission.png")
reset = Vision("daily_reset.jpg")
random = Vision("random.png")
main_menu_original = Vision("main_menu.png")
main_menu = Vision("main_menu_transparent.png")
main_menu_exclamation = Vision("main_menu_exclamation.png")
register_all = Vision("register_all.png")
apply = Vision("apply.png")
salvage = Vision("salvage.png")
salvage_ok = Vision("salvage_ok.png")
back = Vision("back.png")
equipment = Vision("equipment.png")
onslaught = Vision("onslaught.png")
free_stage = Vision("free_stage.png")
auto_repeat_on = Vision("auto_repeat_on.png")
auto_repeat_off = Vision("auto_repeat_off.png")
tavern = Vision("tavern.png")
# equipment_full = Vision("equipment_full.png")
loading_screen = Vision("loading.png")  # Not used
high_grade_equipment = Vision("high_grade_equipment.png")
empty_equipment = Vision("empty_equipment.png")
empty_salvage = Vision("empty_salvage.png")
empty_card_slot = Vision("empty_card_slot.png")
empty_card_slot_2 = Vision("empty_card_slot_2.png")
world = Vision("world.png")
bronze_card = Vision("bronze_card.png")
silver_card = Vision("silver_card.png")
gold_card = Vision("gold_card.png")
auto_off = Vision("autooff.png")
pause = Vision("pause.png")
forfeit = Vision("forfeit.png")
tavern_loading_screen = Vision("tavern_loading_screen.png")

# Equipment farming
auto_repeat_ended = Vision("equipment\\auto_repeat_ended.png")
salvaging_results = Vision("equipment\\salvaging_results.png")

# For Bird farming
demonic_beast = Vision("demonic_beasts\\demonic_beast.png")
hraesvelgr = Vision("demonic_beasts\\hraesvelgr.png")
empty_party = Vision("demonic_beasts\\empty_party.png")
save_party = Vision("demonic_beasts\\save_party.png")
ok_save_party = Vision("demonic_beasts\\OK_save_party.png")
hraesvelgr_screen = Vision("demonic_beasts\\hraesvelgr_screen.png")
skip_bird = Vision("demonic_beasts\\skip_bird_masked.png")
db_loading_screen = Vision("demonic_beasts\\loading_screen.png")
bird_okay = Vision("demonic_beasts\\bird_okay.png")
reset_bird = Vision("demonic_beasts\\reset_bird.png")
my_turn = Vision("demonic_beasts\\my_turn.png")
floor_3_cleard_bird = Vision("demonic_beasts\\floor_3_cleared_bird.png")
floor_3_cleard_2_bird = Vision("demonic_beasts\\floor_3_cleared_2_bird.png")
available_floor = Vision("demonic_beasts\\available_floor.png")
creature_destroyed = Vision("demonic_beasts\\creature_destroyed.png")
defeat = Vision("demonic_beasts\\defeat.png")
ok_bird_defeat = Vision("demonic_beasts\\ok_bird_defeat.png")
three_empty_slots = Vision("demonic_beasts\\three_slots.png")
two_empty_slots = Vision("demonic_beasts\\two_slots.png")
weekly_mission = Vision("demonic_beasts\\lazy_weekly_mission.png")
finished_fight_ok = Vision("demonic_beasts\\finished_fight_ok.png")
forfeit_fight_ok = Vision("demonic_beasts\\forfeit_fight_ok.png")
skollandhati = Vision("demonic_beasts\\skollandhati.png")
phase_1 = Vision("demonic_beasts\\phase_1.png")
phase_2 = Vision("demonic_beasts\\phase_2.png")
phase_3 = Vision("demonic_beasts\\phase_3.png")
phase_4 = Vision("demonic_beasts\\phase_4.png")
guaranteed_reward = Vision("demonic_beasts\\guaranteed_reward.png")
empty_card_slot_dogs = Vision("demonic_beasts\\empty_card_slot_dogs.png")
meli_aoe = Vision("demonic_beasts\\meli_aoe.png")
meli_ult = Vision("demonic_beasts\\meli_ult.png")
meli_ampli = Vision("demonic_beasts\\meli_ampli.png")
block_skill_debuf = Vision("demonic_beasts\\block_skill_debuff.png")
evasion = Vision("demonic_beasts\\evasion.png")
stance_active = Vision("demonic_beasts\\stance_active.png")
immortality_buff = Vision("demonic_beasts\\immortality.png")

# For final boss
final_boss_menu = Vision("final_boss\\final_boss_menu.png")
hell_difficulty = Vision("final_boss\\hell_difficulty.png")
challenge_difficulty = Vision("final_boss\\challenge_difficulty.png")
extreme_difficulty = Vision("final_boss\\extreme_difficulty.png")
hard_difficulty = Vision("final_boss\\hard_difficulty.png")
fb_ok_button = Vision("final_boss\\fb_ok_button.png")
boss_destroyed = Vision("final_boss\\boss_destroyed.png")
boss_results = Vision("final_boss\\boss_results.png")
boss_mission = Vision("final_boss\\boss_mission.png")
episode_clear = Vision("final_boss\\episode_clear.png")
showdown = Vision("final_boss\\showdown.png")
